"""init

Revision ID: 5437fb538d42
Revises: 
Create Date: 2026-04-08 01:32:35.734113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5437fb538d42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_price_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('engine_volume_cc', sa.Integer(), nullable=False),
    sa.Column('car_year', sa.Integer(), nullable=False),
    sa.Column('logistics_cost_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rf_analog_price_rub', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('customs_duty_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recycling_fee_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('usd_to_rub', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('eur_to_rub', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gel_to_rub', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_id'), 'calculations', ['id'], unique=False)
    op.create_index(op.f('ix_calculations_user_id'), 'calculations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculations_user_id'), table_name='calculations')
    op.drop_index(op.f('ix_calculations_id'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
